"""added is_verified and verification_token to users

Revision ID: 550e78c8a69b
Revises: 
Create Date: 2026-03-31 12:56:02.658698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550e78c8a69b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentage_drop', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lookback_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('added_on', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
